#!/usr/bin/env python3
"""
Builds supabase/migrations/022_exercise_plan_library_seed.sql from the
PROGRAMS list defined in generate_exercise_seed.py, attaching each
program's linked_diagnosis_types (giziku's diagnosis_type_enum values:
DM, HT, CHF, CKD, CKD_ND, CKD_HD, CKD_PD, LIVER, CANCER, DYSLIPIDEMIA,
GOUT, GERD, PUD, IBD, OBESITY, MALNUTRITION, SARCOPENIA, POST_OP,
PREGNANCY, LACTATION, PEDIATRIC, GERIATRIC, STROKE, COPD, OTHER).

Run: python3 scripts/build_exercise_seed_migration.py
"""
import json
import sys
import os

sys.path.insert(0, os.path.dirname(__file__))
from generate_exercise_seed import PROGRAMS  # noqa: E402

# diagnosis_code -> list of diagnosis_type_enum values this program serves.
# Many of the 27 library diagnoses are more fine-grained than the app's 25
# enum values, so several map to 'OTHER' (still reachable via diagnosis_code
# / category browsing) plus the closest coarse enum(s) for automatic matching.
LINKED_TYPES = {
    "dm_type2": ["DM"],
    "prediabetes": ["DM", "OTHER"],
    "obesitas": ["OBESITY"],
    "dislipidemia": ["DYSLIPIDEMIA"],
    "hipertensi": ["HT"],
    "gagal_jantung_stabil": ["CHF"],
    "pjk": ["OTHER"],
    "penyakit_arteri_perifer": ["OTHER"],
    "ckd_non_dialysis": ["CKD", "CKD_ND"],
    "hemodialisis": ["CKD_HD"],
    "peritoneal_dialisis": ["CKD_PD"],
    "ppok": ["COPD"],
    "asma": ["OTHER"],
    "long_covid": ["OTHER"],
    "oa_lutut": ["OTHER", "GERIATRIC"],
    "nyeri_punggung_bawah": ["OTHER"],
    "osteoporosis": ["OTHER", "GERIATRIC"],
    "sarcopenia": ["SARCOPENIA"],
    "parkinson": ["OTHER", "GERIATRIC"],
    "pasca_stroke": ["STROKE"],
    "multiple_sclerosis": ["OTHER"],
    "frailty": ["GERIATRIC"],
    "risiko_jatuh": ["GERIATRIC"],
    "kehamilan": ["PREGNANCY"],
    "postpartum": ["LACTATION"],
    "menopause": ["OTHER"],
    "obesitas_anak": ["PEDIATRIC", "OBESITY"],
}


def s(text):
    if text is None:
        return "NULL"
    return "'" + str(text).replace("'", "''") + "'"


def j(obj):
    return s(json.dumps(obj, ensure_ascii=False)) + "::jsonb"


def text_arr(lst):
    if not lst:
        return "'{}'"
    return "ARRAY[" + ",".join(s(x) for x in lst) + "]"


def enum_arr(lst):
    if not lst:
        return "'{}'::diagnosis_type_enum[]"
    return "ARRAY[" + ",".join(s(x) for x in lst) + "]::diagnosis_type_enum[]"


def main():
    missing = [p["diagnosis_code"] for p in PROGRAMS if p["diagnosis_code"] not in LINKED_TYPES]
    if missing:
        raise SystemExit(f"Missing LINKED_TYPES mapping for: {missing}")

    lines = [
        "-- =====================================================================",
        "-- 022_exercise_plan_library_seed.sql",
        "-- Purpose: Seed exercise_programs (27 diagnoses across 9 categories).",
        "-- Generated by scripts/build_exercise_seed_migration.py — edit PROGRAMS",
        "-- in scripts/generate_exercise_seed.py and LINKED_TYPES here, then re-run.",
        "-- Dependencies: 021_exercise_plan_library.sql",
        "-- =====================================================================",
        "",
    ]

    cols = ["category_id", "diagnosis_code", "linked_diagnosis_types", "diagnosis_name_en",
            "diagnosis_name_id", "program_name", "difficulty_level", "target_patient",
            "goals", "fitt", "warmup", "core_exercise", "cooldown", "stretching",
            "media_references", "modifications", "red_flags", "contraindications",
            "monitoring_targets", "progression_rule", "patient_education", "motivation_quote",
            "daily_target_schedule", "evidence_references"]

    for p in PROGRAMS:
        vals = [
            s(p["category_id"]), s(p["diagnosis_code"]), enum_arr(LINKED_TYPES[p["diagnosis_code"]]),
            s(p["diagnosis_name_en"]), s(p["diagnosis_name_id"]), s(p["program_name"]),
            s(p["difficulty_level"]), s(p["target_patient"]),
            j(p["goals"]), j(p["fitt"]), j(p["warmup"]), j(p["core_exercise"]), j(p["cooldown"]),
            j(p["stretching"]), j(p["media_references"]), j(p["modifications"]), j(p["red_flags"]),
            j(p["contraindications"]), j(p["monitoring_targets"]), j(p["progression_rule"]),
            s(p["patient_education"]), s(p["motivation_quote"]), j(p["daily_target_schedule"]),
            text_arr(p["evidence_references"]),
        ]
        stmt = (
            f"INSERT INTO exercise_programs ({', '.join(cols)}) VALUES (\n  "
            + ",\n  ".join(vals)
            + "\n) ON CONFLICT (diagnosis_code, version) DO NOTHING;\n"
        )
        lines.append(stmt)

    out_path = os.path.join(os.path.dirname(__file__), "..", "supabase", "migrations",
                             "022_exercise_plan_library_seed.sql")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Wrote {len(PROGRAMS)} programs -> {out_path}")


if __name__ == "__main__":
    main()
