#!/usr/bin/env python3
"""
Generates 002_exercise_plan_seed.sql for CareLivia's exercise_programs table.
Edit / extend the PROGRAMS list below to add more diagnoses using the same
template, then re-run: python3 generate_seed.py
"""
import json

def s(text):
    if text is None:
        return "NULL"
    return "'" + str(text).replace("'", "''") + "'"

def j(obj):
    return s(json.dumps(obj, ensure_ascii=False)) + "::jsonb"

def arr(lst):
    if not lst:
        return "'{}'"
    return "ARRAY[" + ",".join(s(x) for x in lst) + "]"

PROGRAMS = [

# ============================== METABOLIK ==============================
dict(
  category_id="metabolic", diagnosis_code="dm_type2",
  diagnosis_name_en="Type 2 Diabetes Mellitus", diagnosis_name_id="Diabetes Melitus Tipe 2",
  program_name="Program Jalan Kaki & Latihan Beban untuk DM Tipe 2",
  difficulty_level="pemula",
  target_patient="Pasien DM tipe 2 usia >40 tahun dengan aktivitas fisik rendah, tanpa komplikasi kardiovaskular berat",
  goals=[{"id":"hba1c","label_id":"Menurunkan HbA1c"},{"id":"insulin_sensitivity","label_id":"Meningkatkan sensitivitas insulin"},{"id":"weight","label_id":"Membantu kontrol berat badan"}],
  fitt={"frequency":"5x/minggu (aerobik) + 2-3x/minggu (resistance, hari non-berurutan)","intensity":{"method":"RPE / Talk Test","target":"RPE 11-13, sedang","notes":"Masih bisa bicara, sedikit terengah"},"time":"30-45 menit/sesi aerobik","type":["Jalan kaki","Bersepeda statis","Resistance training ringan"]},
  warmup={"duration_minutes":10,"steps":["Jalan pelan 3-5 menit","Putaran bahu dan pergelangan kaki","Peregangan betis dan paha depan/belakang"]},
  core_exercise={"description":"Kombinasi latihan aerobik intensitas sedang dan resistance training 2 set 8-12 repetisi untuk kelompok otot besar.",
    "weekly_progression":[{"period":"Hari 1","duration_minutes":15,"notes":"Jalan santai"},{"period":"Hari 7","duration_minutes":20,"notes":"Tambah kecepatan bertahap"},{"period":"Minggu 4","duration_minutes":30,"notes":"Target FITT tercapai"},{"period":"Minggu 12","duration_minutes":45,"notes":"Pertahankan, variasikan jenis latihan"}],
    "resistance_details":[{"exercise":"Squat ke kursi","muscle_group":"Quadriceps/Gluteus","sets":2,"reps":10,"rest_seconds":60,"notes":"Gunakan kursi untuk keamanan"},{"exercise":"Wall push-up","muscle_group":"Dada/Triceps","sets":2,"reps":10,"rest_seconds":60}]},
  cooldown={"duration_minutes":5,"steps":["Jalan pelan 2-3 menit","Napas dalam"]},
  stretching={"duration_minutes":5,"steps":["Peregangan hamstring","Peregangan betis","Peregangan bahu"]},
  media_references=[{"phase":"core","label":"Squat ke kursi - posisi awal & akhir","image_url":None,"video_url":None}],
  modifications={"hipertensi":"Hindari manuver Valsava dan angkat beban maksimal","neuropati_perifer":"Pilih latihan non-weight bearing (sepeda, kolam) bila ada luka/mati rasa kaki","retinopati_proliferatif":"Hindari latihan intensitas tinggi dan manuver kepala ke bawah"},
  red_flags=["Gula darah <70 mg/dL sebelum/selama latihan","Gula darah >300 mg/dL disertai keton","Nyeri dada","Pusing atau pandangan kabur mendadak","Sesak napas berat"],
  contraindications={"absolute":["Gula darah >300 mg/dL dengan ketonuria","Hipoglikemia belum teratasi"],"relative":["Ulkus kaki diabetik aktif","Retinopati proliferatif tidak terkontrol"]},
  monitoring_targets=[{"metric":"HbA1c","direction":"decrease","target":"<7%","timeframe":"3 bulan"},{"metric":"Gula darah puasa","direction":"decrease","target":"80-130 mg/dL","timeframe":"berkelanjutan"}],
  progression_rule={"trigger":"2 minggu berturut-turut tanpa keluhan/hipoglikemia","action":"Tambah durasi 10% atau repetisi +2"},
  patient_education="Cek gula darah sebelum dan sesudah latihan pada awal program. Bawa camilan mengandung karbohidrat sederhana bila berlatih lebih dari 30 menit. Hari pertama cukup berjalan santai 15 menit; bila sudah terasa ringan setelah satu minggu, tambah menjadi 20 menit.",
  motivation_quote="Sedikit latihan yang dilakukan rutin jauh lebih bermanfaat daripada latihan berat tapi sesekali.",
  daily_target_schedule={"day_1":"15 menit","day_7":"20 menit","week_4":"30 menit","week_12":"45 menit"},
  evidence_references=["ADA Standards of Care 2024","ACSM Exercise Testing and Prescription","PERKENI 2021"],
),
dict(
  category_id="metabolic", diagnosis_code="prediabetes",
  diagnosis_name_en="Prediabetes", diagnosis_name_id="Prediabetes",
  program_name="Program Aktivitas Fisik Pencegahan Progresi Prediabetes",
  difficulty_level="pemula",
  target_patient="Dewasa dengan gula darah puasa terganggu (IFG) atau toleransi glukosa terganggu (IGT), belum bergejala",
  goals=[{"id":"prevent_progression","label_id":"Mencegah progresi menjadi DM tipe 2"},{"id":"weight","label_id":"Menurunkan berat badan 5-7%"}],
  fitt={"frequency":"5x/minggu","intensity":{"method":"RPE","target":"11-14, sedang","notes":"Total 150 menit/minggu"},"time":"30 menit/sesi","type":["Jalan cepat","Bersepeda","Berenang"]},
  warmup={"duration_minutes":5,"steps":["Jalan pelan 3 menit","Peregangan dinamis ringan"]},
  core_exercise={"description":"Aktivitas aerobik intensitas sedang, dapat dipecah 10 menit x 3 sesi/hari bila belum terbiasa.",
    "weekly_progression":[{"period":"Minggu 1-2","duration_minutes":20,"notes":"Bangun kebiasaan"},{"period":"Minggu 3-6","duration_minutes":30,"notes":"Target harian tercapai"}],
    "resistance_details":[{"exercise":"Resistance band row","muscle_group":"Punggung/Bisep","sets":2,"reps":12,"rest_seconds":45}]},
  cooldown={"duration_minutes":5,"steps":["Jalan pelan","Peregangan"]},
  stretching={"duration_minutes":5,"steps":["Peregangan paha","Peregangan bahu"]},
  media_references=[],
  modifications={"obesitas":"Pilih latihan low-impact (sepeda, kolam) untuk mengurangi beban sendi"},
  red_flags=["Nyeri dada","Sesak napas tidak wajar","Pusing berat"],
  contraindications={"absolute":[],"relative":["Penyakit kardiovaskular tidak terkontrol - perlu skrining dulu"]},
  monitoring_targets=[{"metric":"Gula darah puasa","direction":"decrease","target":"<100 mg/dL","timeframe":"6 bulan"},{"metric":"Berat badan","direction":"decrease","target":"-5% sampai -7%","timeframe":"6 bulan"}],
  progression_rule={"trigger":"Toleransi baik 2 minggu","action":"Tambah 5 menit per sesi"},
  patient_education="Aktivitas fisik teratur, meski ringan, dapat menurunkan risiko diabetes hingga hampir separuh. Mulai dari jalan kaki 20 menit dan tingkatkan bertahap.",
  motivation_quote="Mencegah lebih mudah daripada mengobati — setiap langkah hari ini adalah investasi kesehatan.",
  daily_target_schedule={"day_1":"20 menit","week_6":"30 menit"},
  evidence_references=["ADA 2024","CDC Physical Activity Guidelines"],
),
dict(
  category_id="metabolic", diagnosis_code="obesitas",
  diagnosis_name_en="Obesity", diagnosis_name_id="Obesitas",
  program_name="Program Latihan Low-Impact untuk Penurunan Berat Badan",
  difficulty_level="pemula",
  target_patient="Dewasa dengan IMT ≥30 kg/m², tanpa komplikasi ortopedi berat",
  goals=[{"id":"weight_loss","label_id":"Menurunkan berat badan 5-10%"},{"id":"functional_capacity","label_id":"Meningkatkan kapasitas fungsional"}],
  fitt={"frequency":"5-6x/minggu","intensity":{"method":"RPE","target":"10-13","notes":"Mulai ringan, naik bertahap ke sedang"},"time":"30-60 menit/sesi (boleh dipecah)","type":["Jalan kaki","Berenang","Sepeda statis","Resistance training"]},
  warmup={"duration_minutes":10,"steps":["Jalan pelan","Mobilisasi sendi besar"]},
  core_exercise={"description":"Prioritaskan aktivitas non-weight-bearing di awal (kolam, sepeda) untuk melindungi sendi, lalu tambah weight-bearing bertahap.",
    "weekly_progression":[{"period":"Minggu 1-2","duration_minutes":15,"notes":"2x15 menit/hari"},{"period":"Minggu 8","duration_minutes":45,"notes":"Sesi kontinu"}],
    "resistance_details":[{"exercise":"Sit-to-stand","muscle_group":"Quadriceps/Gluteus","sets":2,"reps":8,"rest_seconds":90}]},
  cooldown={"duration_minutes":5,"steps":["Jalan pelan","Napas dalam"]},
  stretching={"duration_minutes":5,"steps":["Peregangan paha","Peregangan punggung bawah"]},
  media_references=[],
  modifications={"osteoartritis":"Utamakan latihan di air atau bersepeda untuk mengurangi beban sendi","hipertensi":"Hindari menahan napas saat resistance training"},
  red_flags=["Nyeri sendi berat","Nyeri dada","Sesak napas berlebihan","Pusing"],
  contraindications={"absolute":["Gagal jantung dekompensasi"],"relative":["Osteoartritis lutut berat belum dievaluasi"]},
  monitoring_targets=[{"metric":"Berat badan","direction":"decrease","target":"-5% sampai -10%","timeframe":"6 bulan"},{"metric":"Lingkar perut","direction":"decrease","target":"sesuai target individual","timeframe":"6 bulan"}],
  progression_rule={"trigger":"2 minggu tanpa nyeri sendi/keluhan","action":"Tambah durasi 10%"},
  patient_education="Tidak perlu langsung berat. Mulai dari aktivitas yang ringan pada sendi seperti berenang atau bersepeda, lalu tingkatkan durasi secara bertahap setiap minggu.",
  motivation_quote="Penurunan berat badan yang bertahan lama dimulai dari kebiasaan kecil yang konsisten.",
  daily_target_schedule={"day_1":"15 menit","week_8":"45 menit"},
  evidence_references=["ACSM","WHO Physical Activity Guidelines"],
),
dict(
  category_id="metabolic", diagnosis_code="dislipidemia",
  diagnosis_name_en="Dyslipidemia", diagnosis_name_id="Dislipidemia",
  program_name="Program Aerobik untuk Perbaikan Profil Lipid",
  difficulty_level="pemula",
  target_patient="Dewasa dengan LDL tinggi dan/atau HDL rendah, trigliserida tinggi",
  goals=[{"id":"lipid_profile","label_id":"Memperbaiki profil lipid (↓LDL, ↑HDL, ↓trigliserida)"}],
  fitt={"frequency":"5x/minggu","intensity":{"method":"%HRmax","target":"60-75%","notes":"Sedang hingga agak berat"},"time":"30-40 menit/sesi","type":["Jalan cepat","Jogging ringan","Bersepeda"]},
  warmup={"duration_minutes":5,"steps":["Jalan pelan","Peregangan dinamis"]},
  core_exercise={"description":"Latihan aerobik kontinu, intensitas ditingkatkan bertahap untuk memaksimalkan efek pada HDL dan trigliserida.",
    "weekly_progression":[{"period":"Minggu 1-2","duration_minutes":20,"notes":"Intensitas ringan"},{"period":"Minggu 6","duration_minutes":40,"notes":"Intensitas sedang-berat"}],
    "resistance_details":[]},
  cooldown={"duration_minutes":5,"steps":["Jalan pelan"]},
  stretching={"duration_minutes":5,"steps":["Peregangan tungkai"]},
  media_references=[],
  modifications={"hipertensi":"Pantau tekanan darah, hindari peningkatan intensitas mendadak"},
  red_flags=["Nyeri dada","Sesak napas berat","Palpitasi tidak wajar"],
  contraindications={"absolute":[],"relative":["Penyakit jantung koroner belum dievaluasi - skrining EKG dahulu"]},
  monitoring_targets=[{"metric":"LDL","direction":"decrease","target":"sesuai target risiko individual","timeframe":"3 bulan"},{"metric":"HDL","direction":"increase","target":">40 mg/dL (pria) / >50 mg/dL (wanita)","timeframe":"3-6 bulan"}],
  progression_rule={"trigger":"Toleransi baik 2 minggu","action":"Naikkan intensitas 5% HRmax"},
  patient_education="Latihan aerobik rutin adalah salah satu cara paling efektif menaikkan kolesterol baik (HDL) selain obat.",
  motivation_quote="Jantung yang aktif adalah jantung yang sehat.",
  daily_target_schedule={"day_1":"20 menit","week_6":"40 menit"},
  evidence_references=["AHA/ACC Guidelines","ESC Dyslipidemia Guidelines"],
),

# =========================== KARDIOVASKULAR ============================
dict(
  category_id="cardiovascular", diagnosis_code="hipertensi",
  diagnosis_name_en="Hypertension", diagnosis_name_id="Hipertensi",
  program_name="Program Aerobik Terkontrol untuk Hipertensi",
  difficulty_level="pemula",
  target_patient="Pasien hipertensi terkontrol (<160/100 mmHg) tanpa komplikasi organ target berat",
  goals=[{"id":"bp_reduction","label_id":"Menurunkan tekanan darah"},{"id":"cv_risk","label_id":"Menurunkan risiko kardiovaskular"}],
  fitt={"frequency":"5-7x/minggu (aerobik) + 2-3x/minggu resistance ringan","intensity":{"method":"RPE","target":"11-13, sedang","notes":"Hindari intensitas berat"},"time":"30 menit/sesi","type":["Jalan kaki","Bersepeda","Berenang"]},
  warmup={"duration_minutes":10,"steps":["Jalan pelan 5 menit","Peregangan ringan"]},
  core_exercise={"description":"Aerobik kontinu intensitas sedang. Resistance training dengan beban ringan-sedang, hindari menahan napas.",
    "weekly_progression":[{"period":"Minggu 1","duration_minutes":15,"notes":"Mulai perlahan"},{"period":"Minggu 6","duration_minutes":30,"notes":"Target tercapai"}],
    "resistance_details":[{"exercise":"Leg press ringan","muscle_group":"Tungkai","sets":2,"reps":12,"rest_seconds":90,"notes":"Beban ringan, napas tidak ditahan"}]},
  cooldown={"duration_minutes":5,"steps":["Jalan pelan hingga nadi turun"]},
  stretching={"duration_minutes":5,"steps":["Peregangan tungkai dan punggung"]},
  media_references=[],
  modifications={"gagal_jantung":"Turunkan intensitas dan pantau gejala sesak","ckd":"Sesuaikan cairan dan hindari dehidrasi"},
  red_flags=["Nyeri dada","Sakit kepala hebat mendadak","Pandangan kabur","TD sistolik >200 mmHg saat latihan","Pusing berat"],
  contraindications={"absolute":["TD istirahat >180/110 mmHg","Krisis hipertensi"],"relative":["Aritmia tidak terkontrol"]},
  monitoring_targets=[{"metric":"Tekanan darah","direction":"decrease","target":"<130/80 mmHg","timeframe":"3 bulan"}],
  progression_rule={"trigger":"TD stabil dan toleransi baik 2 minggu","action":"Tambah durasi 10%"},
  patient_education="Hindari menahan napas saat mengangkat beban (manuver Valsava) karena dapat menaikkan tekanan darah secara tiba-tiba. Latihan jalan kaki rutin adalah pilihan paling aman untuk memulai.",
  motivation_quote="Setiap langkah membantu jantung bekerja lebih ringan.",
  daily_target_schedule={"day_1":"15 menit","week_6":"30 menit"},
  evidence_references=["ESC/ESH Hypertension Guidelines","AHA","ACSM"],
),
dict(
  category_id="cardiovascular", diagnosis_code="gagal_jantung_stabil",
  diagnosis_name_en="Stable Heart Failure", diagnosis_name_id="Gagal Jantung Stabil",
  program_name="Program Rehabilitasi Kardiak untuk Gagal Jantung Stabil (NYHA I-II)",
  difficulty_level="pemula",
  target_patient="Pasien gagal jantung NYHA kelas I-II, kondisi stabil ≥3 minggu, sudah dievaluasi dokter jantung",
  goals=[{"id":"functional_capacity","label_id":"Meningkatkan kapasitas fungsional (VO2 peak)"},{"id":"quality_of_life","label_id":"Meningkatkan kualitas hidup"}],
  fitt={"frequency":"3-5x/minggu","intensity":{"method":"Borg Scale (RPE 6-20)","target":"11-14","notes":"Mulai sangat ringan, di bawah supervisi awal"},"time":"20-30 menit/sesi, boleh interval","type":["Jalan kaki","Sepeda statis","Latihan interval"]},
  warmup={"duration_minutes":10,"steps":["Jalan sangat pelan 5 menit","Mobilisasi sendi"]},
  core_exercise={"description":"Idealnya dimulai dalam program rehabilitasi kardiak terstruktur dengan supervisi. Gunakan interval kerja-istirahat bila toleransi rendah.",
    "weekly_progression":[{"period":"Minggu 1-2","duration_minutes":10,"notes":"Interval 2 menit kerja/1 menit istirahat, dengan supervisi"},{"period":"Minggu 8-12","duration_minutes":30,"notes":"Kontinu, mandiri bila stabil"}],
    "resistance_details":[{"exercise":"Resistance band ringan","muscle_group":"Otot besar tungkai/lengan","sets":1,"reps":10,"rest_seconds":90,"notes":"Beban sangat ringan"}]},
  cooldown={"duration_minutes":10,"steps":["Jalan sangat pelan","Pantau gejala sesak"]},
  stretching={"duration_minutes":5,"steps":["Peregangan ringan"]},
  media_references=[],
  modifications={"ckd":"Perhatikan status cairan dan elektrolit","aritmia":"Hentikan bila palpitasi tidak wajar"},
  red_flags=["Sesak napas memberat mendadak","Nyeri dada","Berat badan naik >2 kg dalam 2-3 hari","Edema tungkai memberat","Pusing/nyaris pingsan","Palpitasi"],
  contraindications={"absolute":["Gagal jantung dekompensasi akut","Aritmia tidak terkontrol","Stenosis aorta berat simtomatik"],"relative":["Perubahan status klinis dalam 3 hari terakhir"]},
  monitoring_targets=[{"metric":"Kapasitas fungsional (6MWT)","direction":"increase","target":"peningkatan jarak tempuh","timeframe":"12 minggu"},{"metric":"Berat badan harian","direction":"maintain","target":"stabil ±1 kg","timeframe":"harian"}],
  progression_rule={"trigger":"Stabil tanpa gejala 2 minggu, sesuai evaluasi dokter","action":"Tambah durasi 5 menit"},
  patient_education="Timbang berat badan setiap pagi. Jika naik lebih dari 2 kg dalam 2-3 hari atau sesak memberat, hentikan latihan dan segera hubungi dokter.",
  motivation_quote="Latihan yang tepat justru membuat jantung Anda lebih kuat, bukan lebih lelah.",
  daily_target_schedule={"day_1":"10 menit (interval)","week_12":"30 menit (kontinu)"},
  evidence_references=["ESC Heart Failure Guidelines","AHA Cardiac Rehabilitation"],
),
dict(
  category_id="cardiovascular", diagnosis_code="pjk",
  diagnosis_name_en="Coronary Artery Disease", diagnosis_name_id="Penyakit Jantung Koroner",
  program_name="Program Rehabilitasi Kardiak Pasca PJK",
  difficulty_level="pemula",
  target_patient="Pasien pasca sindrom koroner akut/revaskularisasi, sudah menyelesaikan fase rehabilitasi awal di rumah sakit",
  goals=[{"id":"secondary_prevention","label_id":"Pencegahan sekunder kejadian kardiovaskular"},{"id":"functional_capacity","label_id":"Meningkatkan kapasitas aerobik"}],
  fitt={"frequency":"5x/minggu","intensity":{"method":"HRR (Heart Rate Reserve)","target":"40-70% HRR","notes":"Sesuai hasil tes latihan (exercise stress test)"},"time":"20-40 menit/sesi","type":["Jalan kaki","Sepeda statis","Treadmill"]},
  warmup={"duration_minutes":10,"steps":["Jalan pelan","Mobilisasi sendi"]},
  core_exercise={"description":"Program bertahap dimulai dari fase rehabilitasi terawasi, lanjut ke latihan mandiri setelah stabil.",
    "weekly_progression":[{"period":"Minggu 1-4 (fase 2, terawasi)","duration_minutes":20,"notes":"Dengan monitoring EKG bila tersedia"},{"period":"Minggu 12 (fase 3, mandiri)","duration_minutes":40,"notes":"Latihan mandiri dengan evaluasi berkala"}],
    "resistance_details":[{"exercise":"Resistance band","muscle_group":"Otot besar","sets":2,"reps":12,"rest_seconds":90,"notes":"Dimulai setelah minggu ke-4"}]},
  cooldown={"duration_minutes":10,"steps":["Jalan pelan hingga nadi turun ke baseline"]},
  stretching={"duration_minutes":5,"steps":["Peregangan ringan"]},
  media_references=[],
  modifications={"diabetes":"Cek gula darah sebelum latihan","hipertensi":"Pantau TD sebelum dan sesudah"},
  red_flags=["Nyeri dada/angina","Sesak napas tidak wajar","Palpitasi","Pusing","Keringat dingin mendadak"],
  contraindications={"absolute":["Angina tidak stabil","Aritmia mengancam nyawa yang tidak terkontrol","Stenosis aorta berat"],"relative":["Belum dilakukan tes latihan"]},
  monitoring_targets=[{"metric":"Kapasitas fungsional (METs)","direction":"increase","target":"peningkatan bertahap","timeframe":"12 minggu"},{"metric":"Profil lipid & TD","direction":"decrease","target":"sesuai target pencegahan sekunder","timeframe":"3-6 bulan"}],
  progression_rule={"trigger":"Tanpa gejala pada intensitas saat ini selama 1-2 minggu","action":"Naikkan target HR 5% HRR"},
  patient_education="Program rehabilitasi jantung terbukti menurunkan risiko serangan jantung berulang. Ikuti tahapan dengan sabar, jangan memaksakan diri melebihi anjuran dokter.",
  motivation_quote="Pemulihan jantung adalah maraton, bukan sprint — konsistensi adalah kuncinya.",
  daily_target_schedule={"day_1":"20 menit (terawasi)","week_12":"40 menit (mandiri)"},
  evidence_references=["AHA/ACC Cardiac Rehabilitation","ESC Guidelines"],
),
dict(
  category_id="cardiovascular", diagnosis_code="penyakit_arteri_perifer",
  diagnosis_name_en="Peripheral Artery Disease", diagnosis_name_id="Penyakit Arteri Perifer",
  program_name="Program Jalan Kaki Interval untuk Klaudikasio Intermiten",
  difficulty_level="pemula",
  target_patient="Pasien PAD dengan klaudikasio intermiten, ABI rendah, tanpa iskemia kritis tungkai",
  goals=[{"id":"walking_distance","label_id":"Meningkatkan jarak berjalan bebas nyeri"},{"id":"cv_risk","label_id":"Menurunkan risiko kardiovaskular"}],
  fitt={"frequency":"3-5x/minggu","intensity":{"method":"Nyeri klaudikasio sebagai panduan","target":"Jalan sampai nyeri sedang (3-4/5), istirahat, ulangi","notes":"Supervised exercise therapy bila tersedia"},"time":"30-60 menit total (termasuk istirahat)","type":["Jalan kaki interval (treadmill/jalan datar)"]},
  warmup={"duration_minutes":5,"steps":["Peregangan tungkai ringan"]},
  core_exercise={"description":"Jalan kaki sampai timbul nyeri klaudikasio sedang, istirahat hingga reda, ulangi siklus.",
    "weekly_progression":[{"period":"Minggu 1-2","duration_minutes":20,"notes":"Total waktu jalan (interval)"},{"period":"Minggu 12","duration_minutes":50,"notes":"Total waktu jalan meningkat, jarak tanpa nyeri bertambah"}],
    "resistance_details":[]},
  cooldown={"duration_minutes":5,"steps":["Duduk dan istirahat","Elevasi tungkai bila perlu"]},
  stretching={"duration_minutes":5,"steps":["Peregangan betis"]},
  media_references=[],
  modifications={"dm":"Periksa kaki rutin untuk luka, gunakan alas kaki yang tepat","ckd":"Pantau status cairan"},
  red_flags=["Nyeri tungkai saat istirahat (bukan hanya saat aktivitas)","Luka atau perubahan warna kulit kaki yang tidak sembuh","Nyeri dada","Sesak napas"],
  contraindications={"absolute":["Iskemia kritis tungkai (nyeri istirahat, ulkus/gangren)"],"relative":["Penyakit jantung tidak stabil"]},
  monitoring_targets=[{"metric":"Jarak berjalan bebas nyeri","direction":"increase","target":"peningkatan bertahap","timeframe":"12 minggu"},{"metric":"ABI (Ankle-Brachial Index)","direction":"maintain","target":"stabil/membaik","timeframe":"6 bulan"}],
  progression_rule={"trigger":"Toleransi baik 2 minggu","action":"Tambah jumlah siklus interval"},
  patient_education="Nyeri saat berjalan pada PAD sebenarnya adalah bagian dari terapi — berjalan sampai nyeri sedang lalu istirahat justru melatih pembuluh darah membentuk jalur baru.",
  motivation_quote="Setiap langkah, meski disertai nyeri ringan, adalah latihan yang memperkuat sirkulasi Anda.",
  daily_target_schedule={"day_1":"20 menit total","week_12":"50 menit total"},
  evidence_references=["ACC/AHA PAD Guidelines","ESC PAD Guidelines"],
),

# =============================== GINJAL =================================
dict(
  category_id="renal", diagnosis_code="ckd_non_dialysis",
  diagnosis_name_en="Chronic Kidney Disease (Stage 3-4, non-dialysis)", diagnosis_name_id="CKD Stadium 3-4 (Belum Dialisis)",
  program_name="Program Aktivitas Fisik untuk CKD Pra-Dialisis",
  difficulty_level="pemula",
  target_patient="Pasien CKD stadium 3-4, stabil secara klinis, tanpa anemia berat tidak terkoreksi",
  goals=[{"id":"functional_capacity","label_id":"Mempertahankan kapasitas fungsional dan massa otot"},{"id":"bp_control","label_id":"Membantu kontrol tekanan darah"}],
  fitt={"frequency":"3-5x/minggu","intensity":{"method":"RPE","target":"11-13","notes":"Sesuaikan dengan tingkat kelelahan harian"},"time":"20-30 menit/sesi","type":["Jalan kaki","Sepeda statis","Resistance ringan"]},
  warmup={"duration_minutes":5,"steps":["Jalan pelan","Peregangan ringan"]},
  core_exercise={"description":"Intensitas disesuaikan dengan kadar hemoglobin dan tingkat kelelahan; hindari overtraining.",
    "weekly_progression":[{"period":"Minggu 1-2","duration_minutes":15,"notes":"Sesuai toleransi"},{"period":"Minggu 8","duration_minutes":30,"notes":"Bertahap sesuai energi harian"}],
    "resistance_details":[{"exercise":"Resistance band ringan","muscle_group":"Otot besar","sets":2,"reps":10,"rest_seconds":90}]},
  cooldown={"duration_minutes":5,"steps":["Jalan pelan"]},
  stretching={"duration_minutes":5,"steps":["Peregangan ringan"]},
  media_references=[],
  modifications={"anemia":"Turunkan intensitas bila Hb rendah, prioritaskan latihan ringan","hipertensi":"Hindari manuver Valsava"},
  red_flags=["Kelelahan ekstrem","Sesak napas tidak wajar","Nyeri dada","Edema memberat","Pusing berat"],
  contraindications={"absolute":["Anemia berat tidak terkoreksi (sesuai penilaian dokter)","Kondisi akut tidak stabil"],"relative":["Kelelahan berat pada hari tertentu — sesuaikan dengan kondisi"]},
  monitoring_targets=[{"metric":"Kapasitas fungsional","direction":"maintain","target":"stabil/meningkat","timeframe":"3 bulan"},{"metric":"Tekanan darah","direction":"decrease","target":"sesuai target individual","timeframe":"3 bulan"}],
  progression_rule={"trigger":"Toleransi baik dan energi cukup 2 minggu","action":"Tambah durasi 10%"},
  patient_education="Sesuaikan latihan dengan tingkat kelelahan harian. Tidak perlu memaksakan target yang sama setiap hari — dengarkan tubuh Anda.",
  motivation_quote="Menjaga otot tetap aktif membantu tubuh Anda tetap kuat menghadapi perjalanan pengobatan.",
  daily_target_schedule={"day_1":"15 menit","week_8":"30 menit"},
  evidence_references=["KDIGO Guidelines","ACSM"],
),
dict(
  category_id="renal", diagnosis_code="hemodialisis",
  diagnosis_name_en="Hemodialysis", diagnosis_name_id="Hemodialisis",
  program_name="Program Latihan Intradialitik dan Hari Non-Dialisis",
  difficulty_level="pemula",
  target_patient="Pasien hemodialisis rutin, hemodinamik stabil selama sesi HD",
  goals=[{"id":"functional_capacity","label_id":"Meningkatkan kapasitas fungsional"},{"id":"muscle_mass","label_id":"Mencegah sarkopenia/wasting otot"},{"id":"quality_of_life","label_id":"Meningkatkan kualitas hidup"}],
  fitt={"frequency":"3x/minggu (selaras jadwal HD) + hari non-dialisis ringan","intensity":{"method":"RPE","target":"11-13","notes":"Intradialitik: 1-2 jam pertama sesi HD, intensitas ringan-sedang"},"time":"20-30 menit","type":["Sepeda statis intradialitik","Resistance band","Jalan kaki (hari non-HD)"]},
  warmup={"duration_minutes":5,"steps":["Mobilisasi sendi ringan sambil duduk"]},
  core_exercise={"description":"Latihan sepeda statis intradialitik pada 1-2 jam pertama sesi HD (saat hemodinamik paling stabil), atau latihan resistance ringan di hari non-dialisis.",
    "weekly_progression":[{"period":"Minggu 1-2","duration_minutes":10,"notes":"Mulai sangat ringan"},{"period":"Minggu 8","duration_minutes":30,"notes":"Bertahap sesuai toleransi"}],
    "resistance_details":[{"exercise":"Resistance band duduk","muscle_group":"Tungkai/lengan","sets":2,"reps":10,"rest_seconds":90,"notes":"Hindari lengan dengan akses vaskular (AV fistula)"}]},
  cooldown={"duration_minutes":5,"steps":["Istirahat duduk","Pantau tekanan darah"]},
  stretching={"duration_minutes":5,"steps":["Peregangan ringan sambil duduk"]},
  media_references=[],
  modifications={"av_fistula":"Jangan gunakan lengan dengan akses vaskular untuk resistance training","hipotensi_intradialitik":"Hentikan bila tekanan darah turun signifikan"},
  red_flags=["Hipotensi intradialitik (pusing, pandangan gelap)","Kram otot berat","Nyeri dada","Sesak napas","Palpitasi"],
  contraindications={"absolute":["Hemodinamik tidak stabil selama sesi HD","2 jam terakhir sesi HD (risiko hipotensi lebih tinggi)"],"relative":["Akses vaskular baru (<2 minggu)"]},
  monitoring_targets=[{"metric":"Kapasitas fungsional (6MWT)","direction":"increase","target":"peningkatan bertahap","timeframe":"3 bulan"},{"metric":"Massa otot","direction":"maintain","target":"stabil/meningkat","timeframe":"3-6 bulan"}],
  progression_rule={"trigger":"Hemodinamik stabil dan toleransi baik 2 minggu","action":"Tambah durasi 5 menit"},
  patient_education="Latihan ringan selama dua jam pertama sesi cuci darah justru dapat membantu tubuh Anda tetap bugar dan mencegah pengecilan otot.",
  motivation_quote="Menjaga aktivitas selama terapi dialisis adalah investasi untuk kemandirian Anda sehari-hari.",
  daily_target_schedule={"day_1":"10 menit","week_8":"30 menit"},
  evidence_references=["KDIGO","ISRNM Guidelines on Exercise in CKD"],
),
dict(
  category_id="renal", diagnosis_code="peritoneal_dialisis",
  diagnosis_name_en="Peritoneal Dialysis", diagnosis_name_id="Peritoneal Dialisis",
  program_name="Program Latihan Ringan untuk Pasien Peritoneal Dialisis",
  difficulty_level="pemula",
  target_patient="Pasien CAPD/APD stabil, tanpa peritonitis aktif",
  goals=[{"id":"functional_capacity","label_id":"Mempertahankan kapasitas fungsional"},{"id":"muscle_mass","label_id":"Mencegah kehilangan massa otot"}],
  fitt={"frequency":"4-5x/minggu","intensity":{"method":"RPE","target":"10-13","notes":"Ringan hingga sedang"},"time":"20-30 menit/sesi","type":["Jalan kaki","Resistance ringan","Peregangan"]},
  warmup={"duration_minutes":5,"steps":["Mobilisasi ringan"]},
  core_exercise={"description":"Hindari latihan yang meningkatkan tekanan intra-abdomen berlebihan (mengangkat beban berat, sit-up penuh) karena risiko kebocoran dialisat/hernia.",
    "weekly_progression":[{"period":"Minggu 1-2","duration_minutes":15,"notes":"Ringan"},{"period":"Minggu 8","duration_minutes":30,"notes":"Bertahap"}],
    "resistance_details":[{"exercise":"Resistance band tungkai (posisi berdiri/duduk)","muscle_group":"Tungkai","sets":2,"reps":10,"rest_seconds":90,"notes":"Hindari menahan napas/mengejan"}]},
  cooldown={"duration_minutes":5,"steps":["Jalan pelan"]},
  stretching={"duration_minutes":5,"steps":["Peregangan ringan, hindari fleksi perut berlebihan"]},
  media_references=[],
  modifications={"hernia_risiko":"Hindari latihan yang meningkatkan tekanan intra-abdomen","kateter_abdomen":"Lindungi area kateter dari benturan"},
  red_flags=["Nyeri perut mendadak","Cairan dialisat keruh (tanda peritonitis — segera ke fasilitas kesehatan)","Kebocoran cairan di sekitar kateter","Sesak napas","Nyeri dada"],
  contraindications={"absolute":["Peritonitis aktif","Kebocoran dialisat aktif"],"relative":["Pasca insersi kateter <4 minggu — hindari latihan berat"]},
  monitoring_targets=[{"metric":"Kapasitas fungsional","direction":"maintain","target":"stabil/meningkat","timeframe":"3 bulan"}],
  progression_rule={"trigger":"Stabil tanpa keluhan abdomen 2 minggu","action":"Tambah durasi 10%"},
  patient_education="Hindari gerakan yang membuat perut terasa tertekan kuat, seperti mengangkat beban berat, untuk melindungi area kateter dan mencegah hernia.",
  motivation_quote="Aktivitas ringan yang konsisten membantu tubuh Anda tetap bertenaga menjalani terapi.",
  daily_target_schedule={"day_1":"15 menit","week_8":"30 menit"},
  evidence_references=["ISPD Guidelines","KDIGO"],
),

# ============================== RESPIRASI ===============================
dict(
  category_id="respiratory", diagnosis_code="ppok",
  diagnosis_name_en="COPD", diagnosis_name_id="Penyakit Paru Obstruktif Kronik (PPOK)",
  program_name="Program Rehabilitasi Paru untuk PPOK",
  difficulty_level="pemula",
  target_patient="Pasien PPOK stabil (bukan eksaserbasi akut), GOLD grade A-C",
  goals=[{"id":"dyspnea","label_id":"Mengurangi sesak napas saat aktivitas"},{"id":"functional_capacity","label_id":"Meningkatkan toleransi aktivitas"}],
  fitt={"frequency":"3-5x/minggu (aerobik) + 2-3x/minggu (otot pernapasan & resistance)","intensity":{"method":"Skala Sesak Borg (0-10)","target":"4-6/10 (sedang-berat)","notes":"Latihan interval bila sesak berat pada latihan kontinu"},"time":"20-30 menit/sesi","type":["Jalan kaki","Sepeda statis","Latihan pernapasan (pursed-lip breathing)"]},
  warmup={"duration_minutes":5,"steps":["Latihan pernapasan diafragma","Mobilisasi ringan"]},
  core_exercise={"description":"Kombinasi latihan aerobik dan latihan otot pernapasan (pursed-lip breathing, diaphragmatic breathing). Gunakan interval bila sesak signifikan.",
    "weekly_progression":[{"period":"Minggu 1-2","duration_minutes":10,"notes":"Interval singkat dengan istirahat"},{"period":"Minggu 8-12","duration_minutes":30,"notes":"Kontinu, sesuai toleransi"}],
    "resistance_details":[{"exercise":"Resistance band lengan/tungkai","muscle_group":"Otot besar perifer","sets":2,"reps":10,"rest_seconds":60,"notes":"Membantu efisiensi energi sehari-hari"}]},
  cooldown={"duration_minutes":5,"steps":["Pursed-lip breathing","Duduk istirahat"]},
  stretching={"duration_minutes":5,"steps":["Peregangan dada dan bahu"]},
  media_references=[],
  modifications={"hipoksemia":"Gunakan oksigen suplemental saat latihan bila diresepkan dokter","osteoporosis_komorbid":"Hindari latihan high-impact"},
  red_flags=["Sesak napas berat tidak membaik dengan istirahat","Saturasi oksigen turun signifikan (sesuai ambang yang ditetapkan dokter)","Nyeri dada","Sianosis (bibir/kuku kebiruan)","Kebingungan mendadak"],
  contraindications={"absolute":["Eksaserbasi akut PPOK","Gagal napas akut"],"relative":["Aritmia tidak terkontrol"]},
  monitoring_targets=[{"metric":"Toleransi aktivitas (6MWT)","direction":"increase","target":"peningkatan jarak tempuh","timeframe":"8-12 minggu"},{"metric":"Skor sesak (mMRC)","direction":"decrease","target":"penurunan skor","timeframe":"12 minggu"}],
  progression_rule={"trigger":"Sesak terkontrol pada intensitas saat ini selama 1-2 minggu","action":"Tambah durasi 5 menit atau kurangi interval istirahat"},
  patient_education="Gunakan teknik pernapasan bibir mengerucut (pursed-lip breathing) saat merasa sesak: tarik napas lewat hidung, hembuskan perlahan lewat mulut seperti meniup lilin.",
  motivation_quote="Latihan rutin membantu paru-paru Anda bekerja lebih efisien, sehingga aktivitas sehari-hari terasa lebih ringan.",
  daily_target_schedule={"day_1":"10 menit (interval)","week_12":"30 menit (kontinu)"},
  evidence_references=["GOLD Guidelines","American Thoracic Society Pulmonary Rehabilitation"],
),
dict(
  category_id="respiratory", diagnosis_code="asma",
  diagnosis_name_en="Asthma", diagnosis_name_id="Asma",
  program_name="Program Aktivitas Fisik Terkontrol untuk Asma",
  difficulty_level="pemula",
  target_patient="Pasien asma terkontrol baik/sebagian, tanpa serangan dalam 4 minggu terakhir",
  goals=[{"id":"cardio_fitness","label_id":"Meningkatkan kebugaran kardiorespirasi"},{"id":"symptom_control","label_id":"Menjaga kontrol gejala saat beraktivitas"}],
  fitt={"frequency":"3-5x/minggu","intensity":{"method":"RPE","target":"11-14","notes":"Pemanasan lebih panjang untuk mencegah bronkokonstriksi akibat latihan"},"time":"20-30 menit/sesi","type":["Berenang","Jalan kaki","Bersepeda"]},
  warmup={"duration_minutes":10,"steps":["Pemanasan bertahap 10 menit (lebih panjang dari biasa)","Latihan pernapasan"]},
  core_exercise={"description":"Pemanasan panjang penting untuk mencegah exercise-induced bronchoconstriction. Bawa inhaler pereda (reliever) selalu.",
    "weekly_progression":[{"period":"Minggu 1-2","duration_minutes":15,"notes":"Sesuai toleransi"},{"period":"Minggu 8","duration_minutes":30,"notes":"Bertahap"}],
    "resistance_details":[]},
  cooldown={"duration_minutes":10,"steps":["Pendinginan bertahap (tidak berhenti mendadak)","Latihan pernapasan"]},
  stretching={"duration_minutes":5,"steps":["Peregangan dada"]},
  media_references=[],
  modifications={"alergi_lingkungan":"Hindari latihan luar ruangan saat kadar polusi/serbuk sari tinggi atau udara sangat dingin/kering"},
  red_flags=["Mengi/sesak yang tidak membaik dengan inhaler pereda","Sulit bicara karena sesak","Bibir/kuku kebiruan","Batuk berat tidak berhenti"],
  contraindications={"absolute":["Serangan asma akut","Asma tidak terkontrol"],"relative":["Infeksi saluran napas aktif"]},
  monitoring_targets=[{"metric":"Kontrol gejala (ACT score)","direction":"increase","target":"skor terkontrol baik","timeframe":"berkelanjutan"},{"metric":"Kapasitas aerobik","direction":"increase","target":"peningkatan bertahap","timeframe":"12 minggu"}],
  progression_rule={"trigger":"Tanpa gejala saat latihan selama 2 minggu","action":"Tambah durasi 10%"},
  patient_education="Selalu bawa inhaler pereda saat berolahraga. Pemanasan yang cukup panjang membantu mencegah sesak napas yang dipicu oleh latihan.",
  motivation_quote="Dengan kontrol yang baik, asma tidak menghalangi Anda untuk tetap aktif dan bugar.",
  daily_target_schedule={"day_1":"15 menit","week_8":"30 menit"},
  evidence_references=["GINA (Global Initiative for Asthma)","American Thoracic Society"],
),
dict(
  category_id="respiratory", diagnosis_code="long_covid",
  diagnosis_name_en="Long COVID", diagnosis_name_id="Long COVID",
  program_name="Program Pemulihan Bertahap Pasca COVID-19 (Long COVID)",
  difficulty_level="pemula",
  target_patient="Pasien dengan gejala menetap >12 minggu pasca infeksi COVID-19, termasuk kelelahan dan sesak napas",
  goals=[{"id":"fatigue","label_id":"Mengurangi kelelahan pasca-eksersional"},{"id":"functional_capacity","label_id":"Memulihkan kapasitas fungsional secara bertahap"}],
  fitt={"frequency":"Individual, mulai 2-3x/minggu","intensity":{"method":"RPE dengan prinsip pacing","target":"<12 (ringan)","notes":"Prioritaskan pacing, hindari 'push-crash' cycle"},"time":"5-15 menit/sesi di awal, sangat bertahap","type":["Jalan kaki ringan","Latihan pernapasan","Peregangan"]},
  warmup={"duration_minutes":5,"steps":["Latihan pernapasan tenang"]},
  core_exercise={"description":"PENTING: skrining PEM (Post-Exertional Malaise) terlebih dahulu. Jika ada PEM, gunakan prinsip pacing energy conservation, BUKAN peningkatan latihan bertahap standar — prioritaskan istirahat dan aktivitas dalam batas energi, bukan graded exercise therapy.",
    "weekly_progression":[{"period":"Minggu 1-2","duration_minutes":5,"notes":"Sangat ringan, evaluasi respons 24-48 jam"},{"period":"Minggu 8+","duration_minutes":15,"notes":"Naik HANYA jika tidak ada tanda PEM"}],
    "resistance_details":[]},
  cooldown={"duration_minutes":5,"steps":["Istirahat total","Pantau gejala 24-48 jam berikutnya"]},
  stretching={"duration_minutes":5,"steps":["Peregangan sangat ringan"]},
  media_references=[],
  modifications={"pem_positif":"Hentikan pendekatan peningkatan bertahap, fokus pada pacing dan konservasi energi, rujuk ke spesialis"},
  red_flags=["Kelelahan hebat >24 jam setelah aktivitas (PEM)","Sesak napas memberat","Nyeri dada","Palpitasi","Pusing berat/nyaris pingsan","Kabut otak (brain fog) memberat"],
  contraindications={"absolute":["Tanda PEM (Post-Exertional Malaise) signifikan — hindari graded exercise standar"],"relative":["Gejala kardiovaskular belum dievaluasi"]},
  monitoring_targets=[{"metric":"Tingkat kelelahan harian","direction":"decrease","target":"skala kelelahan menurun","timeframe":"individual, bisa berbulan-bulan"},{"metric":"Toleransi aktivitas","direction":"increase","target":"peningkatan sangat bertahap tanpa PEM","timeframe":"individual"}],
  progression_rule={"trigger":"Tidak ada tanda PEM 24-48 jam setelah aktivitas, konsisten 2 minggu","action":"Tambah durasi sangat kecil (1-2 menit)"},
  patient_education="Pemulihan Long COVID berbeda dari latihan biasa — prinsip utamanya adalah 'pacing': lakukan aktivitas dalam batas energi Anda, istirahat sebelum lelah, bukan sesudahnya. Jangan memaksakan diri meski merasa 'hari baik'.",
  motivation_quote="Pemulihan bukan tentang seberapa cepat, tapi seberapa konsisten Anda menjaga keseimbangan energi.",
  daily_target_schedule={"day_1":"5 menit","week_8_plus":"15 menit (jika tanpa PEM)"},
  evidence_references=["NICE Guidelines on Long COVID","WHO Rehabilitation Guidance"],
),

# ========================== MUSKULOSKELETAL =============================
dict(
  category_id="musculoskeletal", diagnosis_code="oa_lutut",
  diagnosis_name_en="Knee Osteoarthritis", diagnosis_name_id="Osteoartritis Lutut",
  program_name="Program Latihan Low-Impact untuk Osteoartritis Lutut",
  difficulty_level="pemula",
  target_patient="Pasien osteoartritis lutut derajat ringan-sedang, nyeri terkontrol",
  goals=[{"id":"pain","label_id":"Mengurangi nyeri lutut"},{"id":"muscle_strength","label_id":"Menguatkan otot quadriceps penstabil lutut"},{"id":"function","label_id":"Meningkatkan fungsi berjalan"}],
  fitt={"frequency":"4-5x/minggu (aerobik) + 2-3x/minggu (penguatan)","intensity":{"method":"RPE / skala nyeri","target":"Nyeri ≤3/10 selama latihan","notes":"Boleh sedikit nyeri ringan, hentikan bila nyeri tajam"},"time":"20-30 menit/sesi","type":["Berenang","Sepeda statis","Latihan penguatan quadriceps"]},
  warmup={"duration_minutes":5,"steps":["Mobilisasi lutut ringan","Jalan pelan"]},
  core_exercise={"description":"Prioritaskan aktivitas low-impact (air, sepeda) dan latihan penguatan otot sekitar lutut untuk mengurangi beban sendi.",
    "weekly_progression":[{"period":"Minggu 1-2","duration_minutes":15,"notes":"Ringan"},{"period":"Minggu 8","duration_minutes":30,"notes":"Bertahap"}],
    "resistance_details":[{"exercise":"Straight leg raise","muscle_group":"Quadriceps","sets":2,"reps":10,"rest_seconds":60},{"exercise":"Mini squat (setengah)","muscle_group":"Quadriceps/Gluteus","sets":2,"reps":10,"rest_seconds":60}]},
  cooldown={"duration_minutes":5,"steps":["Jalan pelan","Kompres dingin bila perlu"]},
  stretching={"duration_minutes":5,"steps":["Peregangan hamstring dan quadriceps ringan"]},
  media_references=[{"phase":"core","label":"Straight leg raise - posisi awal & akhir","image_url":None,"video_url":None}],
  modifications={"obesitas":"Latihan di air untuk mengurangi beban sendi","instabilitas_sendi":"Gunakan brace/penyangga sesuai anjuran fisioterapis"},
  red_flags=["Nyeri tajam mendadak","Bengkak signifikan setelah latihan","Lutut mengunci atau tidak bisa digerakkan","Kemerahan dan hangat pada sendi (curiga infeksi/flare)"],
  contraindications={"absolute":["Flare akut dengan tanda infeksi sendi"],"relative":["Nyeri berat tidak terkontrol - evaluasi dulu"]},
  monitoring_targets=[{"metric":"Skor nyeri (VAS)","direction":"decrease","target":"penurunan skor nyeri","timeframe":"8-12 minggu"},{"metric":"Kekuatan quadriceps","direction":"increase","target":"peningkatan bertahap","timeframe":"12 minggu"}],
  progression_rule={"trigger":"Nyeri terkontrol dan toleransi baik 2 minggu","action":"Tambah repetisi +2 atau durasi 10%"},
  patient_education="Latihan tidak akan memperparah osteoartritis, justru otot yang kuat membantu melindungi sendi. Nyeri ringan setelah latihan yang mereda dalam 24 jam adalah wajar.",
  motivation_quote="Otot yang kuat adalah penyangga terbaik untuk lutut Anda.",
  daily_target_schedule={"day_1":"15 menit","week_8":"30 menit"},
  evidence_references=["OARSI Guidelines","American College of Rheumatology","NICE"],
),
dict(
  category_id="musculoskeletal", diagnosis_code="nyeri_punggung_bawah",
  diagnosis_name_en="Low Back Pain", diagnosis_name_id="Nyeri Punggung Bawah",
  program_name="Program Latihan Penguatan Core untuk Nyeri Punggung Bawah Kronik Non-Spesifik",
  difficulty_level="pemula",
  target_patient="Dewasa dengan nyeri punggung bawah kronik non-spesifik (>12 minggu), tanpa red flag neurologis",
  goals=[{"id":"pain","label_id":"Mengurangi nyeri punggung"},{"id":"core_strength","label_id":"Menguatkan otot core/penyangga tulang belakang"},{"id":"function","label_id":"Meningkatkan fungsi aktivitas harian"}],
  fitt={"frequency":"4-5x/minggu","intensity":{"method":"Skala nyeri","target":"Nyeri ≤3/10","notes":"Tetap aktif, hindari bed rest berkepanjangan"},"time":"20-30 menit/sesi","type":["Jalan kaki","Latihan penguatan core","Yoga/Pilates ringan"]},
  warmup={"duration_minutes":5,"steps":["Jalan pelan","Cat-cow stretch"]},
  core_exercise={"description":"Fokus pada penguatan otot core (transversus abdominis, multifidus) dan tetap aktif secara umum.",
    "weekly_progression":[{"period":"Minggu 1-2","duration_minutes":15,"notes":"Latihan dasar core"},{"period":"Minggu 8","duration_minutes":30,"notes":"Tambah variasi dan repetisi"}],
    "resistance_details":[{"exercise":"Bird-dog","muscle_group":"Core/punggung bawah","sets":2,"reps":10,"rest_seconds":45},{"exercise":"Bridge (pelvic tilt)","muscle_group":"Gluteus/Core","sets":2,"reps":10,"rest_seconds":45}]},
  cooldown={"duration_minutes":5,"steps":["Peregangan ringan","Relaksasi"]},
  stretching={"duration_minutes":5,"steps":["Child's pose","Peregangan hamstring"]},
  media_references=[{"phase":"core","label":"Bird-dog - posisi awal & akhir","image_url":None,"video_url":None}],
  modifications={"osteoporosis":"Hindari fleksi tulang belakang berlebihan dan gerakan memutar mendadak","kehamilan":"Hindari posisi terlentang lama setelah trimester 1"},
  red_flags=["Nyeri menjalar ke tungkai disertai kelemahan/mati rasa","Gangguan buang air kecil/besar (curiga cauda equina — kegawatdaruratan)","Demam disertai nyeri punggung","Nyeri malam hari yang tidak membaik"],
  contraindications={"absolute":["Tanda cauda equina syndrome (segera rujuk gawat darurat)","Fraktur tulang belakang belum stabil"],"relative":["Nyeri radikular akut berat"]},
  monitoring_targets=[{"metric":"Skor nyeri (VAS)","direction":"decrease","target":"penurunan skor","timeframe":"6-8 minggu"},{"metric":"Fungsi (Oswestry Disability Index)","direction":"decrease","target":"penurunan skor disabilitas","timeframe":"8-12 minggu"}],
  progression_rule={"trigger":"Nyeri terkontrol 2 minggu","action":"Tambah repetisi atau variasi latihan"},
  patient_education="Tetap aktif adalah kunci pemulihan nyeri punggung — bed rest berkepanjangan justru memperlambat pemulihan. Nyeri ringan saat mulai bergerak adalah normal dan biasanya mereda.",
  motivation_quote="Gerakan adalah obat terbaik untuk punggung yang kaku.",
  daily_target_schedule={"day_1":"15 menit","week_8":"30 menit"},
  evidence_references=["NICE Low Back Pain Guidelines","American College of Physicians"],
),
dict(
  category_id="musculoskeletal", diagnosis_code="osteoporosis",
  diagnosis_name_en="Osteoporosis", diagnosis_name_id="Osteoporosis",
  program_name="Program Latihan Weight-Bearing dan Keseimbangan untuk Osteoporosis",
  difficulty_level="pemula",
  target_patient="Pasien osteoporosis/osteopenia, risiko jatuh perlu dinilai terlebih dahulu",
  goals=[{"id":"bone_density","label_id":"Mempertahankan/meningkatkan densitas tulang"},{"id":"fall_prevention","label_id":"Mengurangi risiko jatuh"}],
  fitt={"frequency":"3-4x/minggu (weight-bearing) + 2x/minggu (keseimbangan)","intensity":{"method":"RPE","target":"11-13","notes":"Hindari gerakan fleksi tulang belakang berlebihan dan high-impact bila risiko fraktur tinggi"},"time":"20-30 menit/sesi","type":["Jalan kaki","Latihan beban ringan-sedang","Latihan keseimbangan (Tai Chi)"]},
  warmup={"duration_minutes":5,"steps":["Jalan pelan","Mobilisasi sendi"]},
  core_exercise={"description":"Latihan weight-bearing (menahan berat tubuh sendiri) merangsang pembentukan tulang. Hindari gerakan memutar/membungkuk tulang belakang secara tiba-tiba.",
    "weekly_progression":[{"period":"Minggu 1-2","duration_minutes":15,"notes":"Ringan"},{"period":"Minggu 8","duration_minutes":30,"notes":"Bertahap"}],
    "resistance_details":[{"exercise":"Squat ke kursi","muscle_group":"Tungkai","sets":2,"reps":10,"rest_seconds":60},{"exercise":"Heel raise","muscle_group":"Betis","sets":2,"reps":12,"rest_seconds":45}]},
  cooldown={"duration_minutes":5,"steps":["Jalan pelan"]},
  stretching={"duration_minutes":5,"steps":["Peregangan lembut, hindari fleksi tulang belakang dalam"]},
  media_references=[],
  modifications={"risiko_jatuh_tinggi":"Latihan keseimbangan dengan pegangan/pendamping, hindari latihan sendirian","kifosis_berat":"Hindari sit-up dan fleksi tulang belakang"},
  red_flags=["Nyeri tulang belakang mendadak tanpa trauma jelas (curiga fraktur kompresi)","Nyeri hebat setelah jatuh/benturan ringan","Penurunan tinggi badan mendadak disertai nyeri"],
  contraindications={"absolute":["Fraktur kompresi akut belum stabil"],"relative":["Risiko jatuh tinggi belum dievaluasi/diintervensi"]},
  monitoring_targets=[{"metric":"Risiko jatuh (skor fungsional)","direction":"decrease","target":"penurunan risiko","timeframe":"12 minggu"},{"metric":"Densitas tulang (DXA)","direction":"maintain","target":"stabil/meningkat","timeframe":"1-2 tahun"}],
  progression_rule={"trigger":"Tanpa nyeri dan stabil 2 minggu","action":"Tambah beban ringan atau repetisi"},
  patient_education="Latihan menahan berat badan seperti berjalan dan naik-turun tangga membantu memperlambat pengeroposan tulang. Hindari gerakan membungkuk dan memutar tulang belakang secara tiba-tiba.",
  motivation_quote="Tulang yang aktif adalah tulang yang lebih kuat — gerakan hari ini melindungi kemandirian Anda esok hari.",
  daily_target_schedule={"day_1":"15 menit","week_8":"30 menit"},
  evidence_references=["National Osteoporosis Foundation","ACSM"],
),
dict(
  category_id="musculoskeletal", diagnosis_code="sarcopenia",
  diagnosis_name_en="Sarcopenia", diagnosis_name_id="Sarkopenia",
  program_name="Program Resistance Training untuk Sarkopenia",
  difficulty_level="pemula",
  target_patient="Lansia dengan penurunan massa dan kekuatan otot (sarkopenia), fungsional cukup untuk latihan mandiri/terdampingi",
  goals=[{"id":"muscle_mass","label_id":"Meningkatkan massa otot"},{"id":"muscle_strength","label_id":"Meningkatkan kekuatan otot"},{"id":"function","label_id":"Meningkatkan kemampuan fungsional (berjalan, bangun dari kursi)"}],
  fitt={"frequency":"2-3x/minggu (resistance) + aktivitas harian","intensity":{"method":"RPE","target":"12-15","notes":"Progressive resistance training dengan beban meningkat bertahap"},"time":"20-30 menit/sesi","type":["Resistance training","Latihan fungsional (sit-to-stand)"]},
  warmup={"duration_minutes":5,"steps":["Mobilisasi sendi","Jalan pelan"]},
  core_exercise={"description":"Progressive resistance training adalah intervensi paling efektif untuk sarkopenia, ditambah asupan protein cukup (koordinasi dengan Meal Plan).",
    "weekly_progression":[{"period":"Minggu 1-2","duration_minutes":15,"notes":"Beban ringan, fokus teknik"},{"period":"Minggu 12","duration_minutes":30,"notes":"Beban ditingkatkan bertahap"}],
    "resistance_details":[{"exercise":"Sit-to-stand","muscle_group":"Quadriceps/Gluteus","sets":2,"reps":10,"rest_seconds":90},{"exercise":"Resistance band row","muscle_group":"Punggung/Bisep","sets":2,"reps":10,"rest_seconds":90}]},
  cooldown={"duration_minutes":5,"steps":["Jalan pelan"]},
  stretching={"duration_minutes":5,"steps":["Peregangan ringan seluruh tubuh"]},
  media_references=[{"phase":"core","label":"Sit-to-stand - posisi awal & akhir","image_url":None,"video_url":None}],
  modifications={"frailty":"Mulai dengan latihan duduk/dibantu, tingkatkan sangat bertahap","risiko_jatuh":"Latihan dengan pengawasan atau pegangan"},
  red_flags=["Nyeri dada","Pusing berat","Kelelahan ekstrem tidak wajar","Jatuh saat latihan"],
  contraindications={"absolute":["Kondisi akut tidak stabil"],"relative":["Frailty berat - mulai dengan supervisi ketat"]},
  monitoring_targets=[{"metric":"Kekuatan genggam (handgrip strength)","direction":"increase","target":"peningkatan bertahap","timeframe":"12 minggu"},{"metric":"Kecepatan jalan","direction":"increase","target":"peningkatan bertahap","timeframe":"12 minggu"}],
  progression_rule={"trigger":"Toleransi baik dan teknik benar 2 minggu","action":"Tambah beban/resistensi 5-10%"},
  patient_education="Latihan beban, meski ringan, adalah cara paling efektif menjaga otot tetap kuat seiring bertambahnya usia. Pastikan asupan protein cukup untuk mendukung pembentukan otot.",
  motivation_quote="Otot yang kuat menjaga kemandirian Anda dalam beraktivitas sehari-hari.",
  daily_target_schedule={"day_1":"15 menit","week_12":"30 menit"},
  evidence_references=["Asian Working Group for Sarcopenia (AWGS)","ACSM"],
),

# ============================== NEUROLOGI ================================
dict(
  category_id="neurology", diagnosis_code="parkinson",
  diagnosis_name_en="Parkinson's Disease", diagnosis_name_id="Penyakit Parkinson",
  program_name="Program Latihan Fungsional dan Keseimbangan untuk Parkinson",
  difficulty_level="pemula",
  target_patient="Pasien Parkinson stadium ringan-sedang (Hoehn & Yahr I-III), mampu berjalan dengan/tanpa alat bantu",
  goals=[{"id":"mobility","label_id":"Mempertahankan mobilitas dan gaya berjalan"},{"id":"balance","label_id":"Meningkatkan keseimbangan, mengurangi risiko jatuh"},{"id":"quality_of_life","label_id":"Meningkatkan kualitas hidup"}],
  fitt={"frequency":"3-5x/minggu","intensity":{"method":"RPE","target":"12-14","notes":"Lakukan saat efek obat optimal ('on' period)"},"time":"30-45 menit/sesi","type":["Latihan gaya berjalan (big steps)","Tai Chi","Boxing non-kontak","Sepeda statis"]},
  warmup={"duration_minutes":10,"steps":["Mobilisasi sendi","Latihan rotasi tubuh"]},
  core_exercise={"description":"Fokus pada latihan amplitudo besar (gerakan besar dan disengaja), latihan keseimbangan, dan latihan ritmis (musik/hitungan) untuk membantu inisiasi gerakan.",
    "weekly_progression":[{"period":"Minggu 1-2","duration_minutes":20,"notes":"Latihan dasar dengan pendamping"},{"period":"Minggu 12","duration_minutes":45,"notes":"Program terstruktur, bisa mandiri sesuai evaluasi"}],
    "resistance_details":[{"exercise":"Sit-to-stand","muscle_group":"Tungkai","sets":2,"reps":10,"rest_seconds":60}]},
  cooldown={"duration_minutes":10,"steps":["Peregangan","Latihan relaksasi"]},
  stretching={"duration_minutes":5,"steps":["Peregangan fleksor panggul dan dada (sering kaku pada Parkinson)"]},
  media_references=[],
  modifications={"freezing_gait":"Gunakan isyarat visual/auditori (cue) untuk membantu inisiasi langkah","risiko_jatuh":"Latihan dengan pendamping atau di area aman berpegangan"},
  red_flags=["Jatuh berulang","Nyeri dada","Pusing berat/hipotensi ortostatik","Kebingungan mendadak"],
  contraindications={"absolute":["Kondisi kardiovaskular tidak stabil"],"relative":["Freezing gait berat belum dievaluasi terapis"]},
  monitoring_targets=[{"metric":"Keseimbangan (Berg Balance Scale)","direction":"increase","target":"peningkatan skor","timeframe":"12 minggu"},{"metric":"Kecepatan jalan","direction":"increase","target":"peningkatan bertahap","timeframe":"12 minggu"}],
  progression_rule={"trigger":"Stabil tanpa jatuh 2 minggu","action":"Tambah durasi atau kompleksitas latihan keseimbangan"},
  patient_education="Latihan sebaiknya dilakukan saat obat sedang bekerja optimal. Gerakan dengan langkah besar dan sengaja membantu melatih otak mengatasi kekakuan gerak.",
  motivation_quote="Gerakan yang disengaja dan konsisten membantu tubuh Anda tetap lincah.",
  daily_target_schedule={"day_1":"20 menit","week_12":"45 menit"},
  evidence_references=["Movement Disorder Society Guidelines","ACSM"],
),
dict(
  category_id="neurology", diagnosis_code="pasca_stroke",
  diagnosis_name_en="Post-Stroke", diagnosis_name_id="Pasca Stroke",
  program_name="Program Rehabilitasi Fisik Pasca Stroke",
  difficulty_level="pemula",
  target_patient="Pasien pasca stroke fase subakut-kronik, kondisi medis stabil, sudah dievaluasi tim rehabilitasi medik",
  goals=[{"id":"motor_function","label_id":"Memulihkan fungsi motorik sisi yang terkena"},{"id":"functional_capacity","label_id":"Meningkatkan kapasitas aerobik dan mobilitas"},{"id":"fall_prevention","label_id":"Mengurangi risiko jatuh"}],
  fitt={"frequency":"3-5x/minggu (aerobik) + 2-3x/minggu (penguatan/keseimbangan)","intensity":{"method":"RPE","target":"11-14","notes":"Sesuai rekomendasi tim rehabilitasi medik"},"time":"20-40 menit/sesi","type":["Latihan gaya berjalan (dengan/tanpa alat bantu)","Sepeda statis","Latihan penguatan sisi lemah","Latihan keseimbangan"]},
  warmup={"duration_minutes":10,"steps":["Mobilisasi sendi","Peregangan ringan sisi yang lemah"]},
  core_exercise={"description":"Latihan task-specific (spesifik pada aktivitas yang ingin dipulihkan) dikombinasikan dengan latihan aerobik dan penguatan, idealnya dalam program rehabilitasi terstruktur.",
    "weekly_progression":[{"period":"Fase subakut","duration_minutes":20,"notes":"Dengan supervisi fisioterapis"},{"period":"Fase kronik","duration_minutes":40,"notes":"Semi-mandiri dengan evaluasi berkala"}],
    "resistance_details":[{"exercise":"Latihan penguatan sisi lemah (sesuai arahan fisioterapis)","muscle_group":"Sesuai sisi yang terkena","sets":2,"reps":10,"rest_seconds":60}]},
  cooldown={"duration_minutes":5,"steps":["Peregangan","Istirahat"]},
  stretching={"duration_minutes":5,"steps":["Peregangan lembut sisi yang spastik/kaku"]},
  media_references=[],
  modifications={"hemiparesis_berat":"Gunakan alat bantu jalan dan pendampingan penuh","spastisitas":"Koordinasi dengan fisioterapis untuk teknik peregangan yang tepat"},
  red_flags=["Gejala neurologis baru/memburuk (curiga stroke berulang — kegawatdaruratan)","Nyeri dada","Sesak napas berat","Jatuh","Sakit kepala hebat mendadak"],
  contraindications={"absolute":["Kondisi neurologis akut tidak stabil","Kecurigaan stroke berulang - rujuk gawat darurat"],"relative":["Kardiovaskular tidak stabil"]},
  monitoring_targets=[{"metric":"Fungsi motorik (Fugl-Meyer/skala fungsional)","direction":"increase","target":"peningkatan skor","timeframe":"individual, evaluasi berkala"},{"metric":"Mobilitas fungsional","direction":"increase","target":"peningkatan kemandirian ADL","timeframe":"individual"}],
  progression_rule={"trigger":"Evaluasi tim rehabilitasi medik menunjukkan kesiapan","action":"Tingkatkan kompleksitas/durasi latihan"},
  patient_education="Pemulihan pasca stroke membutuhkan latihan yang berulang dan konsisten — otak dan otot belajar kembali gerakan melalui pengulangan. Libatkan keluarga untuk mendukung latihan di rumah.",
  motivation_quote="Setiap pengulangan gerakan adalah langkah kecil menuju kemandirian yang lebih besar.",
  daily_target_schedule={"phase_subacute":"20 menit (terawasi)","phase_chronic":"40 menit"},
  evidence_references=["AHA/ASA Stroke Rehabilitation Guidelines","American Physical Therapy Association"],
),
dict(
  category_id="neurology", diagnosis_code="multiple_sclerosis",
  diagnosis_name_en="Multiple Sclerosis", diagnosis_name_id="Multiple Sclerosis",
  program_name="Program Latihan Adaptif untuk Multiple Sclerosis",
  difficulty_level="pemula",
  target_patient="Pasien MS dalam kondisi remisi/stabil, tanpa relaps aktif",
  goals=[{"id":"fatigue","label_id":"Mengurangi kelelahan"},{"id":"mobility","label_id":"Mempertahankan mobilitas dan kekuatan otot"},{"id":"quality_of_life","label_id":"Meningkatkan kualitas hidup"}],
  fitt={"frequency":"3-4x/minggu","intensity":{"method":"RPE","target":"10-13, ringan-sedang","notes":"Hindari overheating (suhu tubuh naik dapat memperburuk gejala sementara - fenomena Uhthoff)"},"time":"20-30 menit/sesi","type":["Berenang (air sejuk)","Sepeda statis","Latihan penguatan ringan","Yoga adaptif"]},
  warmup={"duration_minutes":5,"steps":["Mobilisasi ringan di lingkungan sejuk"]},
  core_exercise={"description":"Latihan di lingkungan sejuk (kolam renang suhu sedang, ruangan ber-AC) untuk menghindari peningkatan suhu tubuh yang dapat memicu perburukan gejala sementara.",
    "weekly_progression":[{"period":"Minggu 1-2","duration_minutes":15,"notes":"Ringan, pantau kelelahan"},{"period":"Minggu 8","duration_minutes":30,"notes":"Bertahap sesuai energi"}],
    "resistance_details":[{"exercise":"Resistance band ringan","muscle_group":"Otot besar","sets":2,"reps":10,"rest_seconds":90}]},
  cooldown={"duration_minutes":5,"steps":["Pendinginan di lingkungan sejuk"]},
  stretching={"duration_minutes":5,"steps":["Peregangan lembut untuk spastisitas"]},
  media_references=[],
  modifications={"spastisitas":"Koordinasi dengan fisioterapis untuk teknik peregangan","fatigue_berat":"Gunakan prinsip energy conservation, latihan sesi pendek terbagi"},
  red_flags=["Gejala neurologis baru/memburuk signifikan (curiga relaps)","Kelelahan ekstrem tidak membaik dengan istirahat","Gangguan penglihatan mendadak","Suhu tubuh meningkat drastis dengan gejala memburuk"],
  contraindications={"absolute":["Relaps aktif"],"relative":["Kelelahan berat hari itu - sesuaikan atau tunda"]},
  monitoring_targets=[{"metric":"Tingkat kelelahan (Fatigue Severity Scale)","direction":"decrease","target":"penurunan skor","timeframe":"8-12 minggu"},{"metric":"Kekuatan otot","direction":"maintain","target":"stabil/meningkat","timeframe":"12 minggu"}],
  progression_rule={"trigger":"Tanpa perburukan gejala 2 minggu","action":"Tambah durasi 10%"},
  patient_education="Berlatihlah di lingkungan sejuk dan hindari waktu terpanas hari itu, karena suhu tubuh yang naik dapat memicu gejala memburuk sementara. Ini bukan tanda kerusakan permanen dan akan membaik setelah tubuh mendingin.",
  motivation_quote="Latihan yang disesuaikan membantu Anda tetap bugar tanpa memicu gejala berlebih.",
  daily_target_schedule={"day_1":"15 menit","week_8":"30 menit"},
  evidence_references=["National MS Society Exercise Guidelines","ACSM"],
),

# ============================== GERIATRI =================================
dict(
  category_id="geriatric", diagnosis_code="frailty",
  diagnosis_name_en="Frailty", diagnosis_name_id="Frailty (Kerapuhan Lansia)",
  program_name="Program Multikomponen untuk Lansia Frail",
  difficulty_level="pemula",
  target_patient="Lansia dengan sindrom frailty (memenuhi ≥3 kriteria Fried: kelemahan, kelelahan, penurunan aktivitas, gaya berjalan lambat, penurunan berat badan)",
  goals=[{"id":"function","label_id":"Meningkatkan kapasitas fungsional dan kemandirian"},{"id":"muscle_strength","label_id":"Meningkatkan kekuatan otot"},{"id":"fall_prevention","label_id":"Mengurangi risiko jatuh"}],
  fitt={"frequency":"3x/minggu (terstruktur) + aktivitas ringan harian","intensity":{"method":"RPE","target":"10-13, mulai sangat ringan","notes":"Program multikomponen: latihan aerobik, resistance, keseimbangan, fleksibilitas"},"time":"20-30 menit/sesi","type":["Latihan fungsional (sit-to-stand)","Latihan keseimbangan","Jalan kaki dengan/tanpa alat bantu"]},
  warmup={"duration_minutes":5,"steps":["Mobilisasi sendi duduk","Pemanasan ringan"]},
  core_exercise={"description":"Program multikomponen (aerobik + resistance + keseimbangan) idealnya dengan supervisi awal, sangat bertahap. Prioritaskan keamanan.",
    "weekly_progression":[{"period":"Minggu 1-2","duration_minutes":10,"notes":"Sangat ringan, sebagian besar duduk"},{"period":"Minggu 12","duration_minutes":30,"notes":"Bertahap sesuai toleransi dan evaluasi"}],
    "resistance_details":[{"exercise":"Sit-to-stand dari kursi tinggi","muscle_group":"Tungkai","sets":1,"reps":5,"rest_seconds":90,"notes":"Dengan pendampingan"}]},
  cooldown={"duration_minutes":5,"steps":["Istirahat duduk"]},
  stretching={"duration_minutes":5,"steps":["Peregangan ringan sambil duduk"]},
  media_references=[],
  modifications={"risiko_jatuh_sangat_tinggi":"Semua latihan dengan pendampingan langsung, gunakan kursi/dinding untuk pegangan","gangguan_kognitif":"Instruksi sederhana, satu langkah pada satu waktu"},
  red_flags=["Jatuh saat latihan","Nyeri dada","Sesak napas tidak wajar","Kebingungan mendadak","Kelelahan ekstrem"],
  contraindications={"absolute":["Kondisi medis akut tidak stabil"],"relative":["Frailty sangat berat - mulai dengan evaluasi tim geriatri komprehensif"]},
  monitoring_targets=[{"metric":"Kecepatan jalan","direction":"increase","target":"peningkatan bertahap","timeframe":"12 minggu"},{"metric":"Kekuatan genggam","direction":"increase","target":"peningkatan bertahap","timeframe":"12 minggu"}],
  progression_rule={"trigger":"Stabil tanpa jatuh/keluhan 2 minggu, evaluasi positif","action":"Tambah durasi 5 menit atau repetisi +1"},
  patient_education="Latihan sekecil apa pun, seperti berdiri dari kursi beberapa kali sehari, dapat membantu Anda tetap mandiri. Selalu lakukan dengan pendamping di dekat Anda.",
  motivation_quote="Setiap gerakan kecil hari ini adalah langkah menuju kemandirian yang lebih besar.",
  daily_target_schedule={"day_1":"10 menit","week_12":"30 menit"},
  evidence_references=["WHO ICOPE Guidelines","ACSM Geriatric Exercise"],
),
dict(
  category_id="geriatric", diagnosis_code="risiko_jatuh",
  diagnosis_name_en="Fall Risk", diagnosis_name_id="Risiko Jatuh",
  program_name="Program Latihan Keseimbangan untuk Pencegahan Jatuh",
  difficulty_level="pemula",
  target_patient="Lansia dengan riwayat jatuh atau risiko jatuh tinggi (gangguan keseimbangan, gaya berjalan tidak stabil)",
  goals=[{"id":"balance","label_id":"Meningkatkan keseimbangan"},{"id":"fall_prevention","label_id":"Mengurangi frekuensi dan risiko jatuh"},{"id":"confidence","label_id":"Meningkatkan kepercayaan diri bergerak"}],
  fitt={"frequency":"3x/minggu (terstruktur) + latihan keseimbangan harian singkat","intensity":{"method":"RPE","target":"10-12","notes":"Latihan keseimbangan progresif (Otago Exercise Programme atau setara)"},"time":"20-30 menit/sesi","type":["Latihan keseimbangan berdiri","Latihan penguatan tungkai","Jalan dengan tantangan keseimbangan ringan"]},
  warmup={"duration_minutes":5,"steps":["Mobilisasi sendi","Jalan pelan dengan pegangan"]},
  core_exercise={"description":"Latihan keseimbangan progresif seperti berdiri satu kaki (dengan pegangan), tandem walk, dan penguatan tungkai, mengikuti prinsip program terstruktur (mis. Otago).",
    "weekly_progression":[{"period":"Minggu 1-2","duration_minutes":15,"notes":"Dengan pegangan penuh"},{"period":"Minggu 12","duration_minutes":30,"notes":"Tantangan keseimbangan meningkat sesuai evaluasi"}],
    "resistance_details":[{"exercise":"Heel-to-toe walk (tandem walk) dengan pegangan","muscle_group":"Keseimbangan/tungkai","sets":2,"reps":"10 langkah","rest_seconds":60}]},
  cooldown={"duration_minutes":5,"steps":["Duduk istirahat"]},
  stretching={"duration_minutes":5,"steps":["Peregangan ringan tungkai"]},
  media_references=[],
  modifications={"gangguan_penglihatan":"Pastikan pencahayaan baik dan area latihan bebas hambatan","gangguan_kognitif":"Instruksi sederhana dan pengawasan lebih ketat"},
  red_flags=["Jatuh saat latihan","Pusing berat/vertigo","Nyeri dada","Kebingungan mendadak"],
  contraindications={"absolute":["Kondisi akut tidak stabil"],"relative":["Vertigo aktif belum dievaluasi"]},
  monitoring_targets=[{"metric":"Skor keseimbangan (Berg Balance Scale/TUG test)","direction":"increase","target":"perbaikan skor","timeframe":"12 minggu"},{"metric":"Kejadian jatuh","direction":"decrease","target":"penurunan frekuensi jatuh","timeframe":"6-12 bulan"}],
  progression_rule={"trigger":"Stabil tanpa jatuh 2 minggu","action":"Kurangi bantuan pegangan secara bertahap atau tambah kompleksitas"},
  patient_education="Pastikan rumah bebas dari hambatan seperti karpet longgar atau lantai licin. Gunakan alas kaki yang stabil, dan lakukan latihan keseimbangan di dekat pegangan yang kokoh.",
  motivation_quote="Keseimbangan yang lebih baik berarti langkah yang lebih percaya diri setiap hari.",
  daily_target_schedule={"day_1":"15 menit","week_12":"30 menit"},
  evidence_references=["Otago Exercise Programme","CDC STEADI Initiative","WHO ICOPE"],
),

# ================================ WANITA ==================================
dict(
  category_id="women", diagnosis_code="kehamilan",
  diagnosis_name_en="Pregnancy", diagnosis_name_id="Kehamilan",
  program_name="Program Aktivitas Fisik Aman Selama Kehamilan",
  difficulty_level="pemula",
  target_patient="Ibu hamil dengan kehamilan risiko rendah, sudah mendapat izin dokter kandungan",
  goals=[{"id":"fitness","label_id":"Mempertahankan kebugaran kardiovaskular"},{"id":"weight","label_id":"Membantu kontrol penambahan berat badan sesuai target"},{"id":"labor_prep","label_id":"Mempersiapkan tubuh untuk persalinan"}],
  fitt={"frequency":"3-5x/minggu","intensity":{"method":"Talk Test / RPE","target":"11-13, masih bisa bicara nyaman","notes":"Hindari kepanasan berlebih dan dehidrasi"},"time":"20-30 menit/sesi","type":["Jalan kaki","Berenang","Prenatal yoga","Latihan dasar panggul (Kegel)"]},
  warmup={"duration_minutes":5,"steps":["Jalan pelan","Peregangan ringan"]},
  core_exercise={"description":"Hindari posisi terlentang lama setelah trimester pertama, olahraga kontak, dan aktivitas dengan risiko jatuh tinggi.",
    "weekly_progression":[{"period":"Trimester 1","duration_minutes":20,"notes":"Sesuai kebiasaan sebelumnya, sesuaikan bila mual"},{"period":"Trimester 2-3","duration_minutes":30,"notes":"Intensitas dipertahankan, bukan ditingkatkan drastis"}],
    "resistance_details":[{"exercise":"Kegel (dasar panggul)","muscle_group":"Otot dasar panggul","sets":3,"reps":10,"rest_seconds":30}]},
  cooldown={"duration_minutes":5,"steps":["Jalan pelan","Hidrasi cukup"]},
  stretching={"duration_minutes":5,"steps":["Peregangan lembut, hindari peregangan berlebihan (relaksin meningkat)"]},
  media_references=[],
  modifications={"kehamilan_risiko_tinggi":"Konsultasi dokter kandungan sebelum memulai/melanjutkan program apa pun","preeklampsia":"Hindari olahraga hingga dievaluasi dan diizinkan dokter"},
  red_flags=["Perdarahan vagina","Kontraksi teratur sebelum waktunya","Cairan ketuban pecah","Sesak napas berat sebelum aktivitas","Nyeri dada","Sakit kepala hebat","Nyeri/bengkak betis satu sisi (curiga trombosis)","Penurunan gerakan janin"],
  contraindications={"absolute":["Preeklampsia","Plasenta previa setelah 26 minggu","Ketuban pecah dini","Persalinan prematur","Perdarahan persisten trimester 2-3"],"relative":["Anemia berat","Riwayat persalinan prematur"]},
  monitoring_targets=[{"metric":"Penambahan berat badan","direction":"maintain","target":"sesuai rekomendasi IMT pra-hamil","timeframe":"per trimester"},{"metric":"Kebugaran umum","direction":"maintain","target":"stabil, nyaman beraktivitas","timeframe":"sepanjang kehamilan"}],
  progression_rule={"trigger":"Tidak ada — pertahankan intensitas, jangan tingkatkan drastis selama kehamilan","action":"Sesuaikan turun bila muncul ketidaknyamanan"},
  patient_education="Tetap aktif selama kehamilan risiko rendah aman dan bermanfaat untuk ibu dan janin. Dengarkan tubuh Anda — jika merasa sangat lelah atau tidak nyaman, kurangi intensitas.",
  motivation_quote="Tubuh yang aktif membantu mempersiapkan Anda menghadapi persalinan dengan lebih siap.",
  daily_target_schedule={"trimester_1":"20 menit","trimester_2_3":"30 menit"},
  evidence_references=["ACOG Guidelines","WHO Physical Activity Guidelines"],
),
dict(
  category_id="women", diagnosis_code="postpartum",
  diagnosis_name_en="Postpartum", diagnosis_name_id="Pasca Persalinan (Postpartum)",
  program_name="Program Pemulihan Fisik Pasca Persalinan",
  difficulty_level="pemula",
  target_patient="Ibu pasca persalinan normal (mulai ~6 minggu) atau pasca sesar (mulai ~8-10 minggu, sesuai izin dokter)",
  goals=[{"id":"core_recovery","label_id":"Memulihkan kekuatan otot core dan dasar panggul"},{"id":"fitness","label_id":"Mengembalikan kebugaran secara bertahap"},{"id":"mental_health","label_id":"Mendukung kesehatan mental (mengurangi risiko baby blues/depresi)"}],
  fitt={"frequency":"3-5x/minggu","intensity":{"method":"RPE","target":"10-13, mulai ringan","notes":"Mulai dari latihan dasar panggul dan core sebelum latihan intensitas lebih tinggi"},"time":"15-30 menit/sesi","type":["Jalan kaki","Latihan dasar panggul (Kegel)","Latihan core ringan","Yoga postnatal"]},
  warmup={"duration_minutes":5,"steps":["Jalan pelan","Latihan pernapasan"]},
  core_exercise={"description":"Mulai dari latihan dasar panggul dan aktivasi core ringan (transversus abdominis) sebelum kembali ke latihan intensitas lebih tinggi. Periksa diastasis recti bila ada.",
    "weekly_progression":[{"period":"Minggu 6-8","duration_minutes":15,"notes":"Dasar panggul dan jalan kaki ringan"},{"period":"Minggu 12+","duration_minutes":30,"notes":"Bertahap tambah intensitas sesuai evaluasi"}],
    "resistance_details":[{"exercise":"Kegel","muscle_group":"Dasar panggul","sets":3,"reps":10,"rest_seconds":30},{"exercise":"Pelvic tilt","muscle_group":"Core","sets":2,"reps":10,"rest_seconds":45}]},
  cooldown={"duration_minutes":5,"steps":["Jalan pelan"]},
  stretching={"duration_minutes":5,"steps":["Peregangan lembut bahu dan punggung (sering tegang karena menyusui)"]},
  media_references=[],
  modifications={"pasca_sesar":"Tunggu izin dokter (biasanya 8-10 minggu), hindari latihan perut intensif hingga luka pulih","diastasis_recti":"Hindari sit-up penuh, fokus pada latihan core yang aman (koordinasi dengan fisioterapis)"},
  red_flags=["Perdarahan vagina meningkat/berubah warna terang","Nyeri perut hebat","Demam","Nyeri/bengkak tungkai satu sisi","Sesak napas","Tanda-tanda depresi postpartum berat"],
  contraindications={"absolute":["Perdarahan postpartum aktif","Infeksi luka operasi/jahitan"],"relative":["Diastasis recti berat belum dievaluasi"]},
  monitoring_targets=[{"metric":"Kekuatan dasar panggul","direction":"increase","target":"perbaikan fungsi","timeframe":"12 minggu"},{"metric":"Kesejahteraan mental","direction":"increase","target":"perbaikan mood/energi","timeframe":"berkelanjutan"}],
  progression_rule={"trigger":"Pemulihan luka baik dan tanpa nyeri 2 minggu","action":"Tambah durasi/intensitas bertahap"},
  patient_education="Pemulihan pasca persalinan butuh waktu — mulailah dari latihan dasar panggul sebelum kembali ke aktivitas yang lebih berat. Aktivitas fisik ringan juga membantu suasana hati Anda.",
  motivation_quote="Tubuh Anda baru saja melakukan hal luar biasa — beri waktu untuk pulih dengan lembut namun konsisten.",
  daily_target_schedule={"week_6_8":"15 menit","week_12_plus":"30 menit"},
  evidence_references=["ACOG Postpartum Guidelines","Royal Australian and New Zealand College of Obstetricians"],
),
dict(
  category_id="women", diagnosis_code="menopause",
  diagnosis_name_en="Menopause", diagnosis_name_id="Menopause",
  program_name="Program Latihan Komprehensif untuk Wanita Menopause",
  difficulty_level="pemula",
  target_patient="Wanita perimenopause/menopause, dengan perhatian pada kesehatan tulang, jantung, dan berat badan",
  goals=[{"id":"bone_health","label_id":"Menjaga kepadatan tulang"},{"id":"cv_health","label_id":"Menjaga kesehatan kardiovaskular"},{"id":"weight","label_id":"Membantu kontrol berat badan"},{"id":"vasomotor_symptoms","label_id":"Membantu mengurangi gejala vasomotor (hot flashes)"}],
  fitt={"frequency":"5x/minggu (aerobik) + 2-3x/minggu (resistance/weight-bearing)","intensity":{"method":"RPE","target":"11-14","notes":"Kombinasi aerobik dan latihan beban untuk tulang dan otot"},"time":"30 menit/sesi","type":["Jalan cepat","Resistance training","Latihan weight-bearing","Yoga"]},
  warmup={"duration_minutes":5,"steps":["Jalan pelan","Mobilisasi sendi"]},
  core_exercise={"description":"Kombinasi aerobik untuk kesehatan jantung dan resistance/weight-bearing untuk kepadatan tulang, penting karena penurunan estrogen mempercepat kehilangan massa tulang dan otot.",
    "weekly_progression":[{"period":"Minggu 1-2","duration_minutes":20,"notes":"Membangun kebiasaan"},{"period":"Minggu 8","duration_minutes":30,"notes":"Target FITT tercapai"}],
    "resistance_details":[{"exercise":"Squat","muscle_group":"Tungkai","sets":2,"reps":10,"rest_seconds":60},{"exercise":"Resistance band row","muscle_group":"Punggung","sets":2,"reps":10,"rest_seconds":60}]},
  cooldown={"duration_minutes":5,"steps":["Jalan pelan","Pendinginan"]},
  stretching={"duration_minutes":5,"steps":["Peregangan seluruh tubuh"]},
  media_references=[],
  modifications={"osteoporosis_komorbid":"Hindari latihan high-impact dan fleksi tulang belakang berlebihan","hot_flashes_berat":"Latihan di lingkungan sejuk, kenakan pakaian yang menyerap keringat"},
  red_flags=["Nyeri dada","Sesak napas tidak wajar","Perdarahan vagina abnormal pasca-menopause (segera periksa ke dokter)","Nyeri tulang mendadak"],
  contraindications={"absolute":[],"relative":["Penyakit kardiovaskular belum dievaluasi","Osteoporosis berat - sesuaikan jenis latihan"]},
  monitoring_targets=[{"metric":"Berat badan/lingkar perut","direction":"maintain","target":"sesuai target individual","timeframe":"berkelanjutan"},{"metric":"Densitas tulang","direction":"maintain","target":"stabil","timeframe":"1-2 tahun"}],
  progression_rule={"trigger":"Toleransi baik 2 minggu","action":"Tambah durasi 10% atau beban ringan"},
  patient_education="Latihan beban teratur membantu memperlambat pengeroposan tulang dan otot yang sering terjadi setelah menopause, sekaligus membantu mengelola berat badan dan suasana hati.",
  motivation_quote="Fase ini adalah kesempatan baru untuk berinvestasi pada kekuatan dan kesehatan jangka panjang Anda.",
  daily_target_schedule={"day_1":"20 menit","week_8":"30 menit"},
  evidence_references=["North American Menopause Society","ACSM"],
),

# ================================= ANAK ===================================
dict(
  category_id="pediatric", diagnosis_code="obesitas_anak",
  diagnosis_name_en="Childhood Obesity", diagnosis_name_id="Obesitas pada Anak",
  program_name="Program Aktivitas Fisik Menyenangkan untuk Anak dengan Obesitas",
  difficulty_level="pemula",
  target_patient="Anak usia 6-18 tahun dengan IMT di atas persentil 95 sesuai usia dan jenis kelamin",
  goals=[{"id":"weight","label_id":"Membantu perbaikan status berat badan secara bertahap"},{"id":"fitness","label_id":"Meningkatkan kebugaran dan keterampilan motorik"},{"id":"habit","label_id":"Membentuk kebiasaan aktif jangka panjang"}],
  fitt={"frequency":"Setiap hari (total 60 menit/hari sesuai anjuran WHO)","intensity":{"method":"RPE anak / observasi","target":"Sedang-berat, boleh terbagi beberapa sesi","notes":"Fokus pada permainan aktif, bukan 'olahraga terstruktur' semata"},"time":"60 menit/hari (boleh terbagi)","type":["Permainan aktif (kejar-kejaran, lompat tali)","Bersepeda","Berenang","Olahraga tim sesuai minat anak"]},
  warmup={"duration_minutes":5,"steps":["Permainan pemanasan ringan","Peregangan dinamis sederhana"]},
  core_exercise={"description":"Prioritaskan aktivitas berbasis permainan yang menyenangkan untuk anak, melibatkan keluarga, dan mengurangi waktu layar (screen time).",
    "weekly_progression":[{"period":"Minggu 1-2","duration_minutes":30,"notes":"Bangun kebiasaan, boleh terbagi 2x15 menit"},{"period":"Minggu 8","duration_minutes":60,"notes":"Target harian WHO tercapai"}],
    "resistance_details":[{"exercise":"Latihan berbasis berat badan (jumping jack, permainan lompat)","muscle_group":"Seluruh tubuh","sets":2,"reps":"sesuai kemampuan","rest_seconds":60}]},
  cooldown={"duration_minutes":5,"steps":["Jalan pelan","Permainan pendinginan"]},
  stretching={"duration_minutes":5,"steps":["Peregangan sederhana dipandu dengan cara menyenangkan"]},
  media_references=[],
  modifications={"masalah_ortopedi":"Pilih aktivitas low-impact seperti berenang atau bersepeda","kepercayaan_diri_rendah":"Hindari aktivitas kompetitif yang membuat anak merasa dibanding-bandingkan"},
  red_flags=["Nyeri dada","Sesak napas tidak wajar untuk usianya","Pusing/pingsan","Nyeri sendi signifikan"],
  contraindications={"absolute":[],"relative":["Kondisi jantung bawaan belum dievaluasi - skrining dulu bila ada gejala/riwayat"]},
  monitoring_targets=[{"metric":"Status IMT/z-score","direction":"decrease","target":"perbaikan bertahap sesuai kurva pertumbuhan","timeframe":"3-6 bulan"},{"metric":"Waktu layar (screen time)","direction":"decrease","target":"<2 jam/hari (non-akademik)","timeframe":"berkelanjutan"}],
  progression_rule={"trigger":"Anak menikmati aktivitas dan konsisten 2 minggu","action":"Tambah variasi aktivitas atau durasi"},
  patient_education="Ajak anak bermain aktif bersama keluarga, bukan sekadar 'olahraga wajib'. Kurangi waktu layar dan gantikan dengan aktivitas fisik yang disukai anak.",
  motivation_quote="Kebiasaan aktif yang dibangun sejak kecil, dengan cara yang menyenangkan, akan bertahan seumur hidup.",
  daily_target_schedule={"day_1":"30 menit (terbagi)","week_8":"60 menit"},
  evidence_references=["WHO Guidelines on Physical Activity for Children","American Academy of Pediatrics"],
),

]

def main():
    lines = []
    lines.append("-- =====================================================================")
    lines.append("-- CareLivia Clinical Nutrition — Exercise Plan Module")
    lines.append("-- Migration: 002_exercise_plan_seed.sql")
    lines.append("-- Purpose  : Seed exercise_programs across all clinical categories.")
    lines.append("-- Generated by generate_seed.py — edit PROGRAMS list there, not here.")
    lines.append("-- =====================================================================")
    lines.append("")

    cols = ["category_id","diagnosis_code","diagnosis_name_en","diagnosis_name_id","program_name",
            "difficulty_level","target_patient","goals","fitt","warmup","core_exercise","cooldown",
            "stretching","media_references","modifications","red_flags","contraindications",
            "monitoring_targets","progression_rule","patient_education","motivation_quote",
            "daily_target_schedule","evidence_references"]

    for p in PROGRAMS:
        vals = [
            s(p["category_id"]), s(p["diagnosis_code"]), s(p["diagnosis_name_en"]), s(p["diagnosis_name_id"]),
            s(p["program_name"]), s(p["difficulty_level"]), s(p["target_patient"]),
            j(p["goals"]), j(p["fitt"]), j(p["warmup"]), j(p["core_exercise"]), j(p["cooldown"]),
            j(p["stretching"]), j(p["media_references"]), j(p["modifications"]), j(p["red_flags"]),
            j(p["contraindications"]), j(p["monitoring_targets"]), j(p["progression_rule"]),
            s(p["patient_education"]), s(p["motivation_quote"]), j(p["daily_target_schedule"]),
            arr(p["evidence_references"]),
        ]
        stmt = (
            f"insert into public.exercise_programs ({', '.join(cols)}) values (\n  "
            + ",\n  ".join(vals)
            + "\n) on conflict (diagnosis_code, version) do nothing;\n"
        )
        lines.append(stmt)

    with open("002_exercise_plan_seed.sql", "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Generated {len(PROGRAMS)} program rows -> 002_exercise_plan_seed.sql")

if __name__ == "__main__":
    main()
